services:
  ipbot:
    container_name: ipbot
    image: ${DOCKER_REGISTRY}/ipbot
    build:
      context: ./IPBot
      dockerfile: IPBot/Dockerfile
    depends_on:
      - ipbotapi
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  ipbotapi:
    container_name: ipbot-api
    image: ${DOCKER_REGISTRY}/ipbot-api
    build:
      context: ./IPBot.API
      dockerfile: IPBot.API/Dockerfile
    ports:
      - "57890:8080"
      - "57891:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
