version: '3.4'

services:
  ipbot:
    container_name: ipbot
    image: ipbot
    build:
      context: ./IPBot
      dockerfile: IPBot/Dockerfile
    depends_on:
      - ipbotapi
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ipbotapi:
    container_name: ipbotapi
    image: ipbotapi
    build:
      context: ./IPBot.API
      dockerfile: IPBot.API/Dockerfile
    ports:
      - "9000:8080"
      - "9001:8081"
